### ISSUE TITLE
Pluggable fetchers improvements

### ISSUE THREAD

**Issue by oltarasenko** [elixir-crawly/crawly#43]
- [ ] Update Crawly.fetch to use backends
- [ ] Allow specifying fetcher without options

**Comment by Ziinc** [comment]
For your reference @oshosanya 
 
### using backends
Ideally, the Crawly.fetch function should utilize internal functions in worker.ex, request_storage_worker.ex, data_storage_worker.ex to simulate the actual fetching of a request and its returned result. Currently, the logical flow is disjointed from the actual engine backend and implements much of the logic locally instead of reusing it.


### Allow specifying fetcher without options
Currently, fetchers need to be declared in a tuple format as so `{Crawly.Fetchers.HTTPoisonFetcher, []}`, which is due to the way that it is destructured in the worker.ex [here](https://github.com/oltarasenko/crawly/blob/1ec03d765bcdc13a0970d54b1c3f1c8d462e54be/lib/crawly/worker.ex#L83). 

Fetchers should be able to be declared with simply the module name  ,  like so in the config/override_settings: `fetcher: Crawly.Fetchers.HTTPoisonFetcher`, especially for those that do not require additional options.

It should be in line with how middlewares and pipelines are already declared, either by simply the module name, or by tuple format.

The logic should follow what is already used in the `Utils.pipe/3` function https://github.com/oltarasenko/crawly/blob/1ec03d765bcdc13a0970d54b1c3f1c8d462e54be/lib/crawly/utils.ex#L74 , and formatting logic can be abstracted out to its own function.
